# Generated by Django 3.2.3 on 2021-05-23 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timathon", "0010_auto_20201020_0033"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "c1",
                    models.IntegerField(
                        default=1,
                        help_text="Criterion 1",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "c2",
                    models.IntegerField(
                        default=1,
                        help_text="Criterion 2",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "c3",
                    models.IntegerField(
                        default=1,
                        help_text="Criterion 3",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "c4",
                    models.IntegerField(
                        default=1,
                        help_text="Criterion 4",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "c5",
                    models.IntegerField(
                        default=1,
                        help_text="Criterion 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Extra notes", max_length=512, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The submission being judged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="timathon.submission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The judge",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
