# Generated by Django 3.2.4 on 2021-06-07 15:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('timathon', '0013_submission_repl_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='repl_link',
            field=models.CharField(blank=True, help_text='Link to repl', max_length=200, validators=[django.core.validators.RegexValidator(regex=re.compile('https://(replit.com|repl.it)/@[A-Za-z0-9-+_.]+/[A-Za-z0-9.+_-]+'))]),
        ),
    ]
