# Generated by Django 3.2.7 on 2021-09-30 08:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='youtube_video_link',
            field=models.CharField(blank=True, max_length=43, null=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^(https?\\:\\/\\/)?(www\\.)?(youtube\\.com|youtu\\.?be)\\/.+$'))]),
        ),
    ]
